function f = myFUN(u1, u2)
%MYFUN
% F = MYFUN(U1,U2)

% This function was generated by the Symbolic Math Toolbox version 5.9
%    24-Apr-2013 14:20:01

f = [u2-exp(u1.*2.0),u1.*(5.0./4.0)-exp(u2.*3.0)];
